In [2]:
import numpy as np
import pycbc.waveform

In [9]:


# Define the range and step size for chirp mass and mass ratio
chirp_mass_range = np.arange(25.0, 35.1, 0.1)  # Chirp mass in the range (25, 35) with a step of 0.1 M_sun
mass_ratio_range = np.arange(0.5, 1.05, 0.05)  # Mass ratio in the range (0.5, 1.0) with a step of 0.05

# Generate the grid of chirp mass and mass ratio
chirp_masses, mass_ratios = np.meshgrid(chirp_mass_range, mass_ratio_range)

# Flatten the grid to get pairs of (chirp_mass, mass_ratio)
chirp_masses_flat = chirp_masses.flatten()
mass_ratios_flat = mass_ratios.flatten()


[25.  25.1 25.2 25.3 25.4 25.5 25.6 25.7 25.8 25.9 26.  26.1 26.2 26.3
 26.4 26.5 26.6 26.7 26.8 26.9 27.  27.1 27.2 27.3 27.4 27.5 27.6 27.7
 27.8 27.9 28.  28.1 28.2 28.3 28.4 28.5 28.6 28.7 28.8 28.9 29.  29.1
 29.2 29.3 29.4 29.5 29.6 29.7 29.8 29.9 30.  30.1 30.2 30.3 30.4 30.5
 30.6 30.7 30.8 30.9 31.  31.1 31.2 31.3 31.4 31.5 31.6 31.7 31.8 31.9
 32.  32.1 32.2 32.3 32.4 32.5 32.6 32.7 32.8 32.9 33.  33.1 33.2 33.3
 33.4 33.5 33.6 33.7 33.8 33.9 34.  34.1 34.2 34.3 34.4 34.5 34.6 34.7
 34.8 34.9 35.  35.1]
[25.  25.1 25.2 ... 34.9 35.  35.1]
[[25.  25.1 25.2 ... 34.9 35.  35.1]
 [25.  25.1 25.2 ... 34.9 35.  35.1]
 [25.  25.1 25.2 ... 34.9 35.  35.1]
 ...
 [25.  25.1 25.2 ... 34.9 35.  35.1]
 [25.  25.1 25.2 ... 34.9 35.  35.1]
 [25.  25.1 25.2 ... 34.9 35.  35.1]]


In [10]:

# Placeholder for storing waveforms
template_bank = []

# Function to calculate component masses from chirp mass and mass ratio
def component_masses_from_chirp_mass_and_q(chirp_mass, q):
    total_mass = chirp_mass * (1 + q)**(6/5) / q**(3/5)
    m1 = total_mass / (1 + q)
    m2 = total_mass * q / (1 + q)
    return m1, m2

# Generate the template bank using TaylorF2 waveforms
for chirp_mass, q in zip(chirp_masses_flat, mass_ratios_flat):
    m1, m2 = component_masses_from_chirp_mass_and_q(chirp_mass, q)

    # Generate the waveform using TaylorF2 2PN model
    hp, hc = pycbc.waveform.get_fd_waveform(approximant="TaylorF2",
                                            mass1=m1,
                                            mass2=m2,
                                            delta_f=1.0/128,  # Frequency resolution
                                            f_lower=20.0)     # Lower frequency cutoff

    template_bank.append((chirp_mass, q, hp, hc))

# Convert the template bank to a structured array for easier access (optional)
template_bank = np.array(template_bank, dtype=[('chirp_mass', 'f8'), ('mass_ratio', 'f8'), ('hp', 'O'), ('hc', 'O')])

# Display the first few templates
for entry in template_bank[:5]:
    print(f"Chirp Mass: {entry['chirp_mass']}, Mass Ratio: {entry['mass_ratio']}, hp: {entry['hp'][:5]}, hc: {entry['hc'][:5]}")


Chirp Mass: 25.0, Mass Ratio: 0.5, hp: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j], hc: [0.-0.j 0.-0.j 0.-0.j 0.-0.j 0.-0.j]
Chirp Mass: 25.1, Mass Ratio: 0.5, hp: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j], hc: [0.-0.j 0.-0.j 0.-0.j 0.-0.j 0.-0.j]
Chirp Mass: 25.200000000000003, Mass Ratio: 0.5, hp: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j], hc: [0.-0.j 0.-0.j 0.-0.j 0.-0.j 0.-0.j]
Chirp Mass: 25.300000000000004, Mass Ratio: 0.5, hp: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j], hc: [0.-0.j 0.-0.j 0.-0.j 0.-0.j 0.-0.j]
Chirp Mass: 25.400000000000006, Mass Ratio: 0.5, hp: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j], hc: [0.-0.j 0.-0.j 0.-0.j 0.-0.j 0.-0.j]
